### ISSUE TITLE
ipcheck.info cookie not cleared

### ISSUE THREAD

**Issue by practik** [Lusito/forget-me-not#117]
When you do the test at `http://ip-check.info/`, two cookies are set on your machine:
* one from **ip-check.info**
* and one from **ipcheck.info.**

After you close the tab, Forget Me Not clears the first but not the second. I don't know if there's anything you can do about this, since the domain of the second cookie doesn't match the domain of the closed tab. But I still wanted to mention it, since other FMN users are likely to encounter it.

**Comment by Lusito** [comment]
Thanks for the report, I will look into it.

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by Lusito** [comment]
Sorry about this, it completely slipped my mind, as there was a similar issue, for which I created a fix already.
I just ran the test again and ipcheck.info is correctly detected as third-party cookie and gets removed by the "remove third-party cookies" option, even with version 1.0.5.

The next version brings a rewritten code-base. I'll try to get the situation improved, so that the third-party cookies created by a tab get removed on tab close.
