### ISSUE TITLE
Doesn't work in Firefox for Android

### ISSUE THREAD

**Issue by bege10** [Lusito/forget-me-not#118]
This extension can be installed in Firefox for Android, but no cookies nor storage are cleared. Can this be fixed?

**Comment by Lusito** [comment]
Could you tell me what kind of cleanup doesn't work? manual? startup? domain leave?
My Android device was running without issues so far.

**Comment by Lusito** [comment]
LocalStorage cleanup is sadly not yet supported by Firefox, as can be seen here: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browsingData/DataTypeSet

I will make sure to highlight these missing features in the next version.

**Comment by bege10** [comment]
manual? startup? domain leave?

All three don't work.
I unchecked cookies in Firefox privacy settings (delete on exit) and checked domain leave and browser startup in forget me not: whatever I try, cookies are still there in Cookie Manager extension.
As soon as I check cookies in privacy settings they are vanished after startup, of course all of them.

**Comment by sensaval** [comment]
Regarding notification! 
"Show a notification when cookies have been removed". I wish that it would be possible to add for how long Forget Me Not shows notification (in seconds)?
Thanks for a great addon, best "cookie killer" ever.
Forget Me Not to chromium...anything you consider? Can't find any good cookie managers for chromium based browsers (needed for kiwi browser for example).

**Comment by Lusito** [comment]
I have no way to define how long a notification appears. I can close it if it's still there, so it might be possible to close it after x seconds, but if firefox decides to close it before your set interval, there is no way to do avoid this right now. At best I could re-open the notification once it closes, but that is ugly.

I have thought about chromium support, but it's not a high priority, especially since some of the FMN features won't work on chromium and google is currently trying to restrict web-extensions even more. At the very least, I will wait until they finish implementing their "Manifest V3".

**Comment by sensaval** [comment]
Thanks for replay!
Yes Firefox controll notification. And in general everything works greats. There's only problem that I've encountered, is that the notification doesn't disappear sometimes, if I change address (manually or by link), the addon will likely delete some cookies and there by sending new info to Firefox notification, then the notification will disappear after short time as usual. Sending sceenshot, you can se 1 minutes in picture, could wait for 7 min it wouldn't matter.

Thanks!
-------- Originalmeddelande --------
På 9 okt. 2019 22:54, Lusito skrev:

**Comment by Lusito** [comment]
This is getting off-topic. Please create a new issue for this. Also, please write down if this is android-specific. If not, it's likely a bug in firefox.
