### ISSUE TITLE
Add ability to set temporary rules

### ISSUE THREAD

**Issue by ElhemEnohpi** [Lusito/forget-me-not#120]
Thanks for supporting default deny of cookies in issue #50! It would be great if there could also be a way to set a temporary "allow" rule. This could avoid filling up the rules list due to one-time site visits.

I have "Behavior if no rule matches" set to "Block". When I come across a site that's broken by blocked cookies, I'd like the option to set a temporary rule to unbreak it. For example, I could set a red "forget" rule, and when all instances of the domain are closed and the cookies get deleted, the rule itself would get deleted too. This would help avoid building up a huge number of rules for sites I will probably never visit again.

I used to be able to do this with the ["Cookie Controller"](https://web.archive.org/web/20171102000801/https://addons.mozilla.org/en-US/firefox/addon/cookie-controller/) addon. It had a separate, dedicated toolbar button that would create a temporary rule and (optionally) reload the page.

That's the main thing for me, but there could also maybe be a temporary gray rule that would be deleted on restart...

**Comment by Lusito** [comment]
I like the idea.. can't promise when I will get to it, but it sounds like a good thing to have and worth spending some time. Thanks for taking the time writing a detailed use-case!

**Comment by stevesaliman** [comment]
I'd like to second this request.  This was my favorite feature of the old Cookie Monster addon, and I've been looking for a replacement for this feature since Quantum came out.

**Comment by bendover22** [comment]
I agree - "temporary" cookies were one of Cookie Monster's best features to speed the process of allowing cookies on a site that you may never visit again.  

You didn't have to consider, "do I trust this site enough to create a permanent exception?"   Because the rule was gone after Fx closed or you hit "delete cookies."  Now, with the ability to delete cookies (& hopefully soon - temporary rules), it could save time.

I probably wouldn't do the following, but some that don't have time even to click "allow temporary," might make temporary type cookies the default rule if no other rule exists.

In a year's time, I would create 1000's of rules - needed only once, if I created a "forget" rule for every site visited once.  If I use a site multiple times, I can then create a session rule.

*** Didn't I read fairly recently that Mozilla made recent web ext. cookie API changes that allow some cookie manager functions that people asked for in several addons, but weren't possible?  I was in a hurry & didn't bookmark the site & now searching turns up nothing on it.

**Comment by Lusito** [comment]
Will be available in the next version.
