### ISSUE TITLE
Version 2.0 Feedback

### ISSUE THREAD

**Issue by Joel889** [Lusito/forget-me-not#133]
Congrats on releasing version 2.0. This version looks great!
Here are some things I noticed:

1) Clicking on the flower icon while on a blank page / addon page, shows "Invalid Tab". I know why it is doing that, but it could be confusing to some. Perhaps showing the setting tab in those pages might make sense.

2) Missing tooltips under manual clean up.

3) Settings > Cleanup. 
I cannot figure out what "Apply Rules" stands for. What do these settings do differently than "cleanup on domain leave"?
Why are there two "Apply Rules" columns?

If block/remove on creation is turned on, does that mean that all cookies are blocked? If so, then the settings for cleaning them up after domain leave / shutdown etc should be greyed out.

Also, if block/remove on creation is turned off, will this ignore the setting on the bottom for "remove third party cookies on creation"?

I believe a different naming choice or tool-tip explanation will make this more clear.

**Comment by Lusito** [comment]
1) Indeed, a bit confusing, will think about it.
2) True, will investigate.
3) Apply Rules => if not checked, then the respective cleanup will protect data that is protected by never/on startup rules. There is one column to the right of a cleanup type, to which it belongs. I.e. Apply rules on startup and apply rules on domain leave.
4) If block/remove on creation is enabled, then "instantly" rules start working.
5) remove third partxy cookies on creation is unaffected by the above rule.

I guess I could make this more obvious by naming and coloring columns with their respective rule badge character/color rather than using symbols.

**Comment by Joel889** [comment]
> Apply Rules => if not checked, then the respective cleanup will protect data that is protected by never/on startup rules. There is one column to the right of a cleanup type, to which it belongs. I.e. Apply rules on startup and apply rules on domain leave.

I still cannot fully make sense of it. I believe what you are saying is that there are default actions (clean on startup & cleanup on domain leave, which will apply to all domains without any custom rules.

For domains listed under "Define rules" the "apply rules" settings are applied. But only if the domain rule is set to cleanup "On Leave". If the domain rule is set to "Instantly", then the "block/remove on creation" column is used. But then there is another "apply rules" setting, which appears to be using "block/remove on creation" as its parent (otherwise the setting is greyed out). 

Maybe you could include an example for a use case of each of the 5 columns.

**Comment by Lusito** [comment]
Try to look at this example with the manual cleanup:
You have two columns. One that enables the cleanup and one that says `apply rules for this cleanup`.

- If you don't check the first checkbox, this kind of data will not be cleaned during manual cleanup.
- If you check both, then the cleanup will keep rules in mind when doing the cleanup. I.e. rules marked as "Never" or "On Startup" will protect their data.
- If you don't check the apply rules option, then rules will be ignored, i.e. all data will be removed, regardless of rules.

Now look at the cleanup settings tab and look how columns are grouped together by background color. You have a startup cleanup column and a block column, each followed by their own "apply rules" column.

**Comment by Joel889** [comment]
I was able to follow your logic for the manual cleanup functionality.

There seem to be two points of confusion, which make this counter intuitive to understand:
1) The choice of an abigious term "Apply Rules".
2) Checking boxes usually means cleaning, whereas in the "Apply Rules" columns, checking the same box means the opposite (don't clean). 

Maybe instead of calling it "Apply Rules", it should say something like "Clean Custom Domains".

Changing the naming convention would mean inverting the "Apply Rules" check boxes, because currently they really mean "Protect" this data, even though the column before that means "Cleaning".

**Comment by Joel889** [comment]
Also, when greying out the boxes, the check mark inside of it should disappear. Currently, it makes it look like that the action is performed anyway, but cannot be changed. In reality, it just shows whatever previous value the checkbox had prior to disabling its parent.

**Comment by Lusito** [comment]
Some of this is specified in #49. Will try to improve this for the next version

**Comment by Lusito** [comment]
Version 2.1.0 has been released and should make things more clear. Feel free to suggest improvements.

**Comment by practik** [comment]
I'm just going to post this here, because it's related and seems like a very minor comment, but I'd be happy to start a new issue for it instead if you'd prefer.

In the 2.1.0 rules interface, my lovely column heading icons are gone and I'm mad as hell!  Just kidding, the letters are fine – although presumably they must create a tiny bit of extra localization work for you (and what if the words for "on restart," "on domain leave," and "on creation" all start with the same letter in some language?) – and the color-coding is a helpful addition. I would just suggest that the letters should match the tooltip texts, to help users remember what they stand for.

So I would either:

* change the first and last letters to R and C (to match "restart" and "creation" in the tooltip texts)

or:

* change the first and last tooltip texts to "Cleanup on browser start" and "Block/remove instantly" (to match the letters S and I).

This suggestion applies only to the English version, of course.

**Comment by Lusito** [comment]
I can't change the letters, as they are supposed to be in sync with the badge letters. But I should have updated the tooltips to match the badge descriptions (as seen in the rule type selection).

Yes, some languages may have the same letters, but I had that issue with the color coded rule names as well. Usually you can say one and the same thing in different ways in a language. So the translators should try to find a good match.

Created a ticket for the tooltips: #146
