### ISSUE TITLE
Local Storage

### ISSUE THREAD

**Issue by streetwolf** [Lusito/forget-me-not#149]
Unwanted files (Cookies?) located in my Fx profile at /Storage/Default are not being deleted.  I don't know if this is Local Storage or not.  Of note is that CCleaner does delete these files in their cookie cleanup feature.

**Comment by streetwolf** [comment]
I did some research and these are called site data.  I suppose they contain similar stuff as cookies.  Firefox's cookie viewer displays them also.  Is it possible to get rid of them as you do cookies?

**Comment by Lusito** [comment]
Those can usually be cleaned with the local-storage and indexed-db checkboxes. There is, however, a bug preventing indexed-db from being scrubbed correctly in some situations. See #136 for details.

I'm closing this since it seems like a duplicate. If you don't think so, please feel free to clarify.
