### ISSUE TITLE
Preserving localstorage when cleaning cookies

### ISSUE THREAD

**Issue by sn0w** [Lusito/forget-me-not#156]
Is it possible to create a rule that cleans all cookies while preserving some (or all) localstorage keys?

For example I'd like to persist the `theme: dark` setting on https://docs.microsoft.com, which is saved in localstorage, while clearing all of their tracking cookies.

Thanks in advance.

**Comment by Lusito** [comment]
Two things:
Currently it's not possible to clean only some keys in local storage. While it is technically possible, it would be a very hacky solution, since it would require the website to be open and a script to be injected. So don't expect a key specific rules for local storage any time soon.

The use-case clean all cookies, but not local storage is currently possible, although not very convenient, since you need to know all cookie names. You could add A never rule to ms.com and then add cookie-specific forget rules for all cookies.

There has been a feature request for a wildcard in the cookie specific rules (See #137), which would make this easier, but until that is resolved, this is the only way.
