### ISSUE TITLE
Extension breaks paypal payments to planetexpress.com

### ISSUE THREAD

**Issue by monterrr** [Lusito/forget-me-not#195]
The site will open paypal in the same window and when returns says it's awaiting payment eternally, clicking on start snooze solves the problem, I have the settings to clean after 1 second.

**Comment by Lusito** [comment]
That's the intended functionality. When you leave a domain, cleanup happens (unless you have a rule for planetexpress, that says otherwise).

Your usecase is exactly what the snooze button is for. Press the snooze button before you want to do a payment transaction that is on a different website. Afterwards stop snooze to reschedule cleanup.
