### ISSUE TITLE
Youtube cookies are not cleaned on tab closed

### ISSUE THREAD

**Issue by rkuralev** [Lusito/forget-me-not#199]
Firefox 70.0.1 (64-bit) on Ubuntu 18.04 LTS, extension version 2.2.5
Youtube cookies are not deleted when I close all youtube tabs. It doesn't happen even if I manually create a rule to delete all "*.youtube.com" cookies on leave. Local storage for the domain is not cleaned either.

**Comment by Lusito** [comment]
This is most likely a misconfiguration or misunderstanding.
Please check the settings tab if cleanup on domain leave is enabled for cookies and local storage.
Also verify, that no other tab has a youtube video shown at the time of closing the youtube tabs, since embedded youtube videos currently count as if you still have a tab open.

**Comment by rkuralev** [comment]
> no other tab has a youtube video shown at the time of closing the youtube tabs, since embedded youtube videos currently count as if you still have a tab open.

That was the problem!
