### ISSUE TITLE
Cookies not cleared at browser startup

### ISSUE THREAD

**Issue by oz42** [Lusito/forget-me-not#229]
Cookies are not cleared at browser startup which means: after browser startup, I am still logged in into Facebook.

**Comment by Lusito** [comment]
Hello and thanks for the report. Since this is still working correctly here, It is very likely, that you have configured it incorrectly.

You need to enable cleanup on startup in the settings tab of the add-on.

Also your rules need to be configured to remove facebook data. Please check out the tutorial included in the add-on.
