### ISSUE TITLE
Google cookies aren't cleaned on startup anymore

### ISSUE THREAD

**Issue by 001Guy001** [Lusito/forget-me-not#236]
Not sure if it's just something on my end, but about a week ago Google cookies stopped being cleaned.
I removed the rule and created it again and it cleaned fine for one startup but then returned to not cleaning the next day.
(Worth noting that I'm not having the same problem with Reddit cookies which are getting cleaned on startup just fine)
**Edit:** so I just tested it again and now Google cookies were removed but Reddit cookies weren't. Not sure what's going on.

**Comment by Lusito** [comment]
What is your indicator that cookies are not deleted? If google/reddit remembers something about you that doesn't have to be a cookie. could be localStorage or indexedDB as well.

You can use this page to try cleanup:
https://lusito.github.io/forget-me-not/

**Comment by 001Guy001** [comment]
There are times where I open the browser and I'm still logged in to Google (and now also Reddit).
It used to work fine up to maybe a week ago and nothing really changed that I know of.
FMN is set up to clean LS and iDB as well.
I set https://lusito.github.io/forget-me-not/ to Instantly, but it says it still remembers me after I close the tab and go to the page again.

**Comment by Lusito** [comment]
Does it remember you on all parts or just some parts? IndexedDB and ServiceWorkers can not yet be cleaned per Domain yet.

I just tried this myself and I get this:

```
Cookie: I don't remember you
Local Storage: I don't remember you
IndexedDB: I remember you
ServiceWorker: I remember you
```
Which is expected, since indexedDB and ServiceWorker support is only coming in Version 3 (and Firefox 77)

- Open the Popup and on the first tab, check if the chosen rules are reflecting what you expect.
- Check if some of your checkboxes in the settings pages are disabled
- Check if the cleanup delay is set to the amount you want
- Check the log to see if there domains have the correct rule labels associated with them
- Check the cookie browser to see if the cookies have the correct rule labels associated with them
- Check if you have snooze mode enabled

If none of these show you where you have a wrong configuration, you can send me your config and I'll check if I can reproduce the issue.

Also, please note, which browser and version you are using.

**Comment by 001Guy001** [comment]
My bad, I didn't have Instantly enabled. Now it doesn't remember anything :)
Anyway, the problem is with the On Startup cleanup. All of Google cookies are set to be deleted on startup and LS is checked along with Apply Rules next to it.
I'm attaching my current settings:
[forget-me-not-settings.zip](https://github.com/Lusito/forget-me-not/files/4673381/forget-me-not-settings.zip)

**Comment by Lusito** [comment]
So, I tried reproducing with your config and it cleans up cookies and localStorage correctly.

So, I can see two things happening here:
- You keep tabs open, which either have google running or google running in an iframe (something embedded like a youtube player)
  - On startup, FMN checks if domains are still open regarding that domain. Cleanup will only run if the domain is not open on startup.
- You have other extensions installed and something weird happens when they are combined with FMN.

(I'm starting to think though that it's a bad idea to protect open domains on startup. Gonna have to think about this more.)

**Comment by 001Guy001** [comment]
I have a Google Doc tab that's always open. But that was always the case, and it worked perfectly fine (I was logged off at startup) up until maybe a week ago.
I haven't installed any new addons recently, and none of them deal with what FMN deals with so I'm not sure they could interfere. But here are the ones that were recenlty updated, let me know if you thing any of these could be related to this:
- Feedbro (updated on May 11)
- Ignore X-Frame-Options (May 20)
- HTTPS Everywhere (May 21)
- uBlock Origin (May 23)

Oh and I forgot to say that I'm on Firefox 76.0.1

**Comment by Lusito** [comment]
If it worked before, then maybe something in Firefox changed, so that the startup of extensions and tabs was different. Fact is, that if you have a tab open, cleanup is not supposed to happen according to the current logic.

As said, I'll think about changing that, so that startup cleanup will always happen. Or I'll make another option for the user to choose.

**Comment by 001Guy001** [comment]
Alright, thanks a bunch! :)
