### ISSUE TITLE
Resizable dialogs

### ISSUE THREAD

**Issue by milupo** [Lusito/forget-me-not#28]
Hi Lusito,

please make dialogs resizable, e.g. settings window. It is important for translations into other languages where the strings can be longer than the English ones. I sent you the Upper Sorbian and Lower Sorbian translation and because of a word with three letters the tab titles in the settings window are truncated with Lower Sorbian.

Thanks

**Comment by Lusito** [comment]
Sorry about the delay. I'm aware of the issue. There is a problem with removing the fixed width tho: The wider the popup, the smaller it will be on a mobile screen. Making it harder to use for mobile users.

There are ways to solve this. I'm just not sure which path to choose:
- Creating an alternative to tabs (for example a dropdown) on mobile
- Using multiple tab rows (I never liked this approach tho, since it feels overloaded)
- Using icons instead of text on the tab
- Removing a tab or combining some of them
  - The settings tab is already getting quite crowded and would be split into subtabs eventually.. putting the rules tab inside those subtabs might be an option.
- Converting some of the tabs into action buttons.. I.E. a symbol to click on, which would then move away from the tabs UI to a simple UI with a "back" button.
  - the cleanup and the log tabs might be good choices for this.

Let me know what you think.

**Comment by milupo** [comment]
Hi Lusito,

the most important thing is that the space should not be limited, it is not for Sorbian languages but also for other languages that have longer strings than English.

- I don't know if you can realize responsive design
- Multiple tab rows, I don't like them, either
- Icons are not always meaningful enough

Well, first of all I would remove this enlarged FMN flower icon in the settings tab bar. There will be still space enough for Sorbian if this space is used for tabs. It is sufficient to have the FMN icon in the toolbar.

You could use a navigation sidebar as Firefox settings do. The tabs are one below the other then. You will have the content to the right then and content lines you can wrap. But, the navigation bar should be wide enough as well so it should use min-width, just as precaution.

Regards,
Michael
