### ISSUE TITLE
What does clear "Service Workers" do?

### ISSUE THREAD

**Issue by Joel889** [Lusito/forget-me-not#36]
What does clear "Service Workers" do, and what are the implications of doing that? 
I mean, why wouldn't someone want to clean them?

**Comment by Lusito** [comment]
I haven't read deeply into it, but from what I gather, Service Workers are a way to allow webapps to keep running even when the network connection is lost. Performing computations in the background, intercepting network requests:
https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API

I've mostly included this cleaning option since it was available in the API and users might want it at some point, when service workers are used in more websites (currently, I know no websites which do).

Hope this helps.
