### ISSUE TITLE
Some cookies not being auto-deleted

### ISSUE THREAD

**Issue by Joel889** [Lusito/forget-me-not#40]
Go to github.com, close tab, cookies remain even after the timer-based cleaning mechanism has run.
There are no whitelist/greylist etc settings for that domain.
Manually running clean-up gets rid of them.

**Comment by Joel889** [comment]
Do you know when you'll have time to fix this? It's sort of a big problem that directly affects the addon's main functionality.

**Comment by Lusito** [comment]
It's actually fixed in the code already.. the Problem I have right now is that mozilla removed the possibility to release beta versions, so I'll have to extensively test the new code all by myself before releasing a new version (and there are many things to keep in mind).

The past few weeks I was busy getting a new apartment in the city where my new job is and driving back and forth between cities. I finally got one, so I should be able to put some time into it. Hopefully I'll be able to release a new version within the week.

Sorry about the delay.

**Comment by Joel889** [comment]
It appears this is still an issue, but to a much lesser extend. I'm not sure how to reproduce it, but even without having any whitelist, there are a few cookies that did not get deleted automatically even with all tabs closed for a while.

**Comment by Joel889** [comment]
Download anything from sourceforge [.] net. This particular 3rd party cookie isn't being removed, even though 3rd party auto cleaning is enabled. The cookie disappears when clearing manually through the extension.

**Comment by Lusito** [comment]
Thanks for the example, I will try to reproduce it.
