### ISSUE TITLE
Questionnable default selection

### ISSUE THREAD

**Issue by Aggrobatics** [Lusito/forget-me-not#44]
I do not think that 'white' is a good default selection, as it seems to denote the browser's standard behaviour (if I am not mistaken). Wouldn't 'grey' be more likely to be selected?

**Comment by Lusito** [comment]
The default behaviour or the browser when forget me not is active, is "forget", i.e. red. So white is your exception to this default rule. People usually want some comfort. Not having to log in to their favorite website everytime they open a browser. To me it seems like white is perfectly fine as a default value.

Feel free to add arguments to convince me otherwise.
