### ISSUE TITLE
Suggestion: display existing cookies (or open FF cookie manager)

### ISSUE THREAD

**Issue by OhSoGood** [Lusito/forget-me-not#56]
If Firefox 57+ allows it, that would be great to have a quick way in Forget-me-not to display existing cookies, notably if you implement the by-cookie authorization (display cookie > click on one > select allow or forbid). 

If too complex, a simple button to open the Firefox cookie manager would be great also. Today, to access FF cookie manager is a long process involving several clics, scrolls & co.

**Comment by Lusito** [comment]
I thought about adding a button to show the firefox cookie manager. See #9.
There is a url you can use to see the manager, but it's not allowed to open this from within the extension. You can enter it manually into the URL-bar:
chrome://browser/content/preferences/cookies.xul

I guess it would be possible to make a simple list that is just for adding rules and place that functionality under the "current tab" tab somewhere.

It will have to wait for now tho, since I want to spend some time on improving the quality & stability of the code for the next version by adding more unit tests.

I'm closing this issue, as #9 already covers the issue.
