### ISSUE TITLE
Occasionally cookies aren't removed, but storage from YouTube never is.

### ISSUE THREAD

**Issue by 53245342099** [Lusito/forget-me-not#61]
It's not whitelisted.  Not sure what could be causing it.  Please let me know if you need any further information from me.  

Love the addon.

**Comment by Lusito** [comment]
Hi,

first of all, thanks for reporting. These are two issues. However, I'm positive, that at least the storage is just a naming confusion because firefox is not really informative in that regard.

If you go to preferences and click on the "manage data.." button, which shows cookies as well as "storage", then firefox fooled you with bad naming. The storage listed here is not "Local Storage", but rather "Indexed DB". Local Storage is not listed in that popup at all. Don't ask me why.

Sadly, there is currently no way to remove indexedDB data by hostname, so I am unable to clear that data upon tab-leave without removing everything else as well.

As for the cookies not being removed.. I would need more information about those cookies.
I have fixed a couple of issues with the next version, so hopefully your bug will be fixed as well then.

So you can either wait for the next version and see if it was fixed or give me some more information about what cookies are not being cleared correctly. In #59 you can see what issues might be at hand here.

Thanks again.

**Comment by Lusito** [comment]
Closing this for now.. if this continues to be an issue, please re-open
