### ISSUE TITLE
More Clearing Feature

### ISSUE THREAD

**Issue by Riajyuu** [Lusito/forget-me-not#69]
1. clean when close a tab (regardless of others instances of a domain):
    - forward and/or backward history
    - cookie and/or Local Storage
2. clean when leaving all instances of a domain:
    - search & form history
3. change delay unit from `minute(s)` into `second(s)`

To do 1 & 2, may have to reconsider the UI arrangement.

**Comment by Lusito** [comment]
1. Could you explain your use-cases for this?
Cleaning cookies and storage in these situations would very likely break a lot of webpages.

2. I guess cleaning form data would not cause any problems. It wouldn't be limited to the domain tho. It would be all form data and this would have to be communicated clearly.

3. You can enter decimal values, so if you want half a minute, enter 0.5. I guess this could be made more comfortable tho. I have added it to the list of #67

**Comment by kroka** [comment]
Motivation for cleaning after a tab was closed (except the part _"regardless of others instances of a domain"_):

An order in a web shop recently failed as the extension has – as expected – deleted the shop's cookies after I was redirected to an external payment page (PayPal in this case). Once I was redirected back to the shop, the order was not finalized as the system missed the cookies. Deleting the cookies only once a tab was closed (similar to https://github.com/Cookie-AutoDelete/Cookie-AutoDelete) would prevent this issue. 

Of course, other solutions for this use case are already possible (longer delay; white / gray listing of the web shop).

**Comment by Lusito** [comment]
Then your description for 1. was confusing.. it read like you wanted to clear when a tab was closed, even if other tabs with that domain where still open.. which would break the other tab instances.

What you want is to clean on tab close rather than on domain leave. Since this would cause cookies to remain long after a domain was left, I would not recommend this approach.

I'd warmly suggest the snooze button for this kind of thing, as this is exactly the use-case it was written for.
1. Go to shopping domain
2. Press Snooze
3. Purchase stuff
4. Press Unsnooze => all cleanups that will be rescheduled

**Comment by kroka** [comment]
@Lusito I've–more or less–hijacked this thread. I guess you've understood @Rictusempra's slightly different suggestion correctly.

Thanks for your hint on the snoozing feature!

**Comment by Lusito** [comment]
Oh yeah, sorry. I wasn't paying attention to the usernames.. I'm a bit tired at the moment.

**Comment by Lusito** [comment]
Closing this due to lack of feedback
