### ISSUE TITLE
Forget me not seemingly not working together with containers

### ISSUE THREAD

**Issue by Speravir** [Lusito/forget-me-not#74]
I started to open some sites in dedicated containers (using the addon [Containerise](https://addons.mozilla.org/firefox/addon/containerise/) but it would probably have worked a bit more complicated with [Firefox Multi-Account Containers](https://addons.mozilla.org/firefox/addon/multi-account-containers/), too). One a these sites is YouTube which I had set to gray, especially because of the annoying autoplay (I've set it off once in a session). With containers I noticed now, that the gray switch actually is not granted – Youtube acts like it would be set to white (apart from the autoplay it also remembered visited pages and suggested new videos accordingly, too creepy for me). So now Youtube is set to red, but then I have to switch off autoplay several times a day, when the interval between video watchings have been too long. (Well, as a workaround I could avoid opening YT in a container …)

**Comment by Lusito** [comment]
Let me summarize to make sure I get your issue right:
- You've set youtube to gray
- You use containers, one of them with youtube opened.

I'm also assuming these:
- You've enabled the "clean on browser start" option including the cookies option for this option. (since gray would just act as white if you didn't enable this option)
- You close firefox and after a browser restart, cookies still exist?

I will try to investigate this, but since I'm leaving for a vacation in a couple of days, I won't have too much time.

**Comment by Speravir** [comment]
> You've set youtube to gray
> You use containers, one of them with youtube opened.

Yes for both.

> You've enabled the "clean on browser start" option including the cookies option for this option.

Yes, too.

> You close firefox and after a browser restart, cookies still exist?

I do not know, I did not check this. I just noticed the different behaviour in YouTube which quite probably needs saved cookies: Remembering which pages/videos I have watched and whether autostart is switched off (and only because of the latter I used the gray domain in Forget Me Not, not red).

Actually, after writing the issue message I’ve removed YouTube from the one’s to be opened in a container. And now it works again like wanted. Now, all sites I let open in a container aren’t configured in forget me not and are therefore set to red.

**Comment by Lusito** [comment]
Thanks for the info, I will investigate this after I return from my vacation.

**Comment by Lusito** [comment]
Sorry about the delay.. it's been a busy month.
I have good and bad news.

**Good news**:
I've identified the issue. Firefox doesn't list all cookie stores, as it's supposed to.. only those that are currently in open tabs.
I have filed a bug for this on bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1486274

**Bad News**:
Ideally this should be fixed by Mozilla, but from my experience, it may take years for them to do anything about it.
So I'm gonna have to find a workaround for this. It looks like I can't get around requesting permissions for contextualIdentities (container tabs), meaning Forget Me Not will activate container tabs for every user, even if they don't want do (Firefox does this when an extension requests the permission). They will have to disable it manually in the settings. I had hoped this could be avoided.

**Comment by Speravir** [comment]
Thank you, nonetheless. Hopefully, this leads to an improvement of Firefox.

I don’t know whether this is helpful, but I noticed that the addon [Cookie Quick Manager](https://addons.mozilla.org/firefox/addon/cookie-quick-manager/) does show me all cookies, also from containers (but I think nothing from the storage), so I can delete now at least these manually.
